import { type Notification } from '@/types/notification';

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    type: 'found_pet',
    status: 'unread',
    title: 'Someone found your pet!',
    message: 'Click here to see if this pet belongs to you',
    timestamp: '2025-09-27T09:00:00Z',
    imageUrl: '/images/onboarding/pet.svg',
    actionUrl: '/notification/1',
    petId: 4,
    petType: 'dog',
    location: 'Central Park, Manhattan',
    finderName: 'Sarah Johnson',
  },
  {
    id: '2',
    type: 'missing_pet',
    status: 'unread',
    title: 'Missing pets nearby',
    message: 'Open here to see missing pets near your location',
    timestamp: '2025-09-27T09:00:00Z',
    imageUrl: '/images/onboarding/pet-3.svg',
    actionUrl: '/notification/2',
    petId: 3,
    petName: 'Max',
    petType: 'dog',
    location: 'Brooklyn Heights',
    bounty: 500,
  },
  {
    id: '3',
    type: 'sighting_report',
    status: 'unread',
    title: 'Comment',
    message: 'Someone commented on your post: "Thank you four more longing..."',
    timestamp: '2025-09-27T09:00:00Z',
    imageUrl: '/images/onboarding/pet-2.svg',
    actionUrl: '/notification/3',
    petId: 1,
    petName: 'Whiskers',
    reporterName: 'Mike Chen',
    location: 'Brooklyn Heights',
    confidence: 'high',
  },
  {
    id: '4',
    type: 'match_alert',
    status: 'unread',
    title: 'Trending',
    message: 'Your pet is Trending in the Fun Section',
    timestamp: '2025-09-27T09:00:00Z',
    imageUrl: '/images/onboarding/pet.svg',
    actionUrl: '/notification/4',
    lostPetId: 3,
    foundPetId: 5,
    matchScore: 85,
    location: 'Times Square',
  },
  {
    id: '5',
    type: 'bounty_update',
    status: 'unread',
    title: 'Update',
    message: 'Download the new app version and get new features',
    timestamp: '2025-09-27T12:34:00Z',
    imageUrl: '/images/onboarding/pet-3.svg',
    actionUrl: '/notification/5',
    petId: 2,
    petName: 'Buddy',
    oldBounty: 750,
    newBounty: 1000,
  },
];
